import {
  FileText, Eye, Brain, Calendar, CheckCircle, Clock,
  Shield, ArrowRightCircle, CheckCircle2,
} from "lucide-react";
import type { BrainStatus, WorkflowStage } from "./demandAnalysisReport.types";

// ============================================================================
// DEMAND ANALYSIS REPORT - UTILITY FUNCTIONS
// ============================================================================

export function getBrainStatus(workflowStatus?: string): BrainStatus {
  if (workflowStatus === "pending_approval" || workflowStatus === "validation") {
    return {
      label: "Pending Approval",
      badgeClass: "bg-blue-500/10 text-blue-600 border-blue-500/20",
      nextGate: "PMO Director approval",
    };
  }

  if (workflowStatus === "resubmitted") {
    return {
      label: "Resubmitted",
      badgeClass: "bg-cyan-500/10 text-cyan-600 border-cyan-500/20",
      nextGate: "Human acknowledgement",
    };
  }

  if (workflowStatus === "rejected") {
    return {
      label: "Blocked",
      badgeClass: "bg-red-500/10 text-red-600 border-red-500/20",
      nextGate: "Revision or withdrawal",
    };
  }

  if (workflowStatus === "requires_more_info" || workflowStatus === "deferred") {
    return {
      label: "Needs Info",
      badgeClass: "bg-amber-500/10 text-amber-600 border-amber-500/20",
      nextGate: "Clarification",
    };
  }

  if (
    workflowStatus === "acknowledged" ||
    workflowStatus === "approved" ||
    workflowStatus === "manager_approved" ||
    workflowStatus === "pending_conversion" ||
    workflowStatus === "converted" ||
    workflowStatus === "completed"
  ) {
    return {
      label: "Approved",
      badgeClass: "bg-emerald-500/10 text-emerald-600 border-emerald-500/20",
      nextGate: "Execution",
    };
  }

  if (workflowStatus === "manager_approval") {
    return {
      label: "Final Approval",
      badgeClass: "bg-blue-500/10 text-blue-600 border-blue-500/20",
      nextGate: "Director signoff",
    };
  }

  if (workflowStatus === "initially_approved") {
    return {
      label: "Pre-Approved",
      badgeClass: "bg-indigo-500/10 text-indigo-600 border-indigo-500/20",
      nextGate: "Director review",
    };
  }

  if (workflowStatus === "meeting_scheduled") {
    return {
      label: "Review Scheduled",
      badgeClass: "bg-purple-500/10 text-purple-600 border-purple-500/20",
      nextGate: "Panel review",
    };
  }

  if (workflowStatus === "under_review") {
    return {
      label: "In Review",
      badgeClass: "bg-yellow-500/10 text-yellow-700 border-yellow-500/20",
      nextGate: "Validation",
    };
  }

  return {
    label: "Generated",
    badgeClass: "bg-slate-500/10 text-slate-600 border-slate-500/20",
    nextGate: "Review",
  };
}

export function getWorkflowStages(): WorkflowStage[] {
  return [
    {
      id: "generated",
      label: "Generated",
      icon: FileText,
      description: "Report generated by AI",
      color: "bg-gray-500/10 border-gray-500/20 text-gray-700 dark:text-gray-300",
      gradient: "from-gray-500/5 to-gray-600/5",
    },
    {
      id: "resubmitted",
      label: "Resubmitted",
      icon: FileText,
      description: "Updated request returned to acknowledgement",
      color: "bg-cyan-500/10 border-cyan-500/20 text-cyan-700 dark:text-cyan-300",
      gradient: "from-cyan-500/5 to-cyan-600/5",
    },
    {
      id: "acknowledged",
      label: "Acknowledged",
      icon: Eye,
      description: "Request acknowledged by team",
      color: "bg-blue-500/10 border-blue-500/20 text-blue-700 dark:text-blue-300",
      gradient: "from-blue-500/5 to-blue-600/5",
    },
    {
      id: "under_review",
      label: "Under Review",
      icon: Brain,
      description: "Currently being analyzed",
      color: "bg-yellow-500/10 border-yellow-500/20 text-yellow-700 dark:text-yellow-300",
      gradient: "from-yellow-500/5 to-yellow-600/5",
    },
    {
      id: "meeting_scheduled",
      label: "Meeting Scheduled",
      icon: Calendar,
      description: "Stakeholder meeting planned",
      color: "bg-purple-500/10 border-purple-500/20 text-purple-700 dark:text-purple-300",
      gradient: "from-purple-500/5 to-purple-600/5",
    },
    {
      id: "initially_approved",
      label: "Initial Approval",
      icon: CheckCircle,
      description: "Initially approved by reviewer",
      color: "bg-emerald-500/10 border-emerald-500/20 text-emerald-700 dark:text-emerald-300",
      gradient: "from-emerald-500/5 to-emerald-600/5",
    },
    {
      id: "manager_approval",
      label: "Pending Final Approval",
      icon: Clock,
      description: "Awaiting director final approval",
      color: "bg-amber-500/10 border-amber-500/20 text-amber-700 dark:text-amber-300",
      gradient: "from-amber-500/5 to-amber-600/5",
    },
    {
      id: "manager_approved",
      label: "Approved",
      icon: Shield,
      description: "Final approval obtained",
      color: "bg-green-500/10 border-green-500/20 text-green-700 dark:text-green-300",
      gradient: "from-green-500/5 to-green-600/5",
    },
    {
      id: "pending_conversion",
      label: "Pending Conversion",
      icon: ArrowRightCircle,
      description: "Awaiting PMO approval for project conversion",
      color: "bg-indigo-500/10 border-indigo-500/20 text-indigo-700 dark:text-indigo-300",
      gradient: "from-indigo-500/5 to-indigo-600/5",
    },
    {
      id: "converted",
      label: "Converted",
      icon: CheckCircle2,
      description: "Successfully converted to project",
      color: "bg-teal-500/10 border-teal-500/20 text-teal-700 dark:text-teal-300",
      gradient: "from-teal-500/5 to-teal-600/5",
    },
    {
      id: "completed",
      label: "Workflow Complete",
      icon: CheckCircle2,
      description: "Workflow closed as complete",
      color: "bg-emerald-500/10 border-emerald-500/20 text-emerald-700 dark:text-emerald-300",
      gradient: "from-emerald-500/5 to-emerald-600/5",
    },
  ];
}

export function getWorkflowStatusColor(status: string): string {
  switch (status) {
    case "resubmitted":
      return "bg-cyan-100 text-cyan-800 dark:bg-cyan-900 dark:text-cyan-200";
    case "generated":
      return "bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200";
    case "acknowledged":
      return "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200";
    case "meeting_scheduled":
      return "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200";
    case "under_review":
      return "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200";
    case "requires_more_info":
      return "bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200";
    case "initially_approved":
      return "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200";
    case "approved":
      return "bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200";
    case "manager_approval":
      return "bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200";
    case "manager_approved":
      return "bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200";
    case "pending_conversion":
      return "bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200";
    case "converted":
      return "bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200";
    case "completed":
      return "bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200";
    case "deferred":
      return "bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200";
    case "rejected":
      return "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200";
    default:
      return "bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200";
  }
}

export function getWorkflowStatusLabel(status: string): string {
  switch (status) {
    case "resubmitted":
      return "RESUBMITTED";
    case "generated":
      return "GENERATED";
    case "acknowledged":
      return "ACKNOWLEDGED";
    case "meeting_scheduled":
      return "MEETING SCHEDULED";
    case "under_review":
      return "UNDER REVIEW";
    case "requires_more_info":
      return "REQUIRES MORE INFO";
    case "initially_approved":
      return "INITIALLY APPROVED";
    case "approved":
      return "APPROVED";
    case "manager_approval":
      return "PENDING FINAL APPROVAL";
    case "manager_approved":
      return "APPROVED";
    case "pending_conversion":
      return "PENDING CONVERSION";
    case "converted":
      return "CONVERTED TO PROJECT";
    case "completed":
      return "WORKFLOW COMPLETE";
    case "deferred":
      return "DEFERRED";
    case "rejected":
      return "REJECTED";
    default:
      return status?.replace("_", " ").toUpperCase() || "UNKNOWN";
  }
}

export function hasDemandResubmission(
  workflowHistory?: Array<{ newStatus?: string | null; reason?: string | null; correction?: unknown }> | null,
): boolean {
  return Boolean(workflowHistory?.some((entry) => {
    if (entry.newStatus !== "generated") return false;
    if ("correction" in entry) return true;
    return /correct|resubmit|updated/i.test(entry.reason || "");
  }));
}

export function resolveDemandDisplayWorkflowStatus(
  workflowStatus?: string | null,
  workflowHistory?: Array<{ newStatus?: string | null; reason?: string | null; correction?: unknown }> | null,
): string {
  const status = workflowStatus || "generated";
  if (status === "generated" && hasDemandResubmission(workflowHistory)) {
    return "resubmitted";
  }
  return status;
}
