import type { IStorage } from ".";

import * as identityRepo from "./repositories/identity.repository";
import * as demandRepo from "./repositories/demand.repository";
import * as versioningRepo from "./repositories/versioning.repository";
import * as knowledgeRepo from "./repositories/knowledge.repository";
import * as complianceRepo from "./repositories/compliance.repository";
import * as intelligenceRepo from "./repositories/intelligence.repository";
import * as portfolioRepo from "./repositories/portfolio.repository";
import * as governanceRepo from "./repositories/governance.repository";
import * as performanceRepo from "./repositories/performance.repository";
import * as learningRepo from "./repositories/learning.repository";
import * as eaRegistryRepo from "./repositories/ea-registry.repository";

/**
 * PostgreSQL implementation of IStorage interface
 * Government-grade persistence with transactional safety and audit logging
 * Compliant with UAE Vision 2071 requirements
 *
 * Thin delegator — domain logic lives in ./repositories/*.repository.ts
 */
export class PostgresStorage implements IStorage {
  // ===== IDENTITY =====
  getUser = identityRepo.getUser;
  getUserByUsername = identityRepo.getUserByUsername;
  createUser = identityRepo.createUser;
  getUserByEmail = identityRepo.getUserByEmail;
  updateUser = identityRepo.updateUser;
  deleteUser = identityRepo.deleteUser;
  getAllUsers = identityRepo.getAllUsers;
  getUsersByRole = identityRepo.getUsersByRole;
  getUsersWithPermission = identityRepo.getUsersWithPermission;
  createAuditLog = identityRepo.createAuditLog;
  getAuditLogs = identityRepo.getAuditLogs;
  createNotification = identityRepo.createNotification;
  getUserNotifications = identityRepo.getUserNotifications;
  getUnreadNotifications = identityRepo.getUnreadNotifications;
  markNotificationAsRead = identityRepo.markNotificationAsRead;
  markAllNotificationsAsRead = identityRepo.markAllNotificationsAsRead;
  deleteNotification = identityRepo.deleteNotification;

  // ===== DEMAND =====
  getDemandReport = demandRepo.getDemandReport;
  getAllDemandReports = demandRepo.getAllDemandReports;
  getDemandReportsList = demandRepo.getDemandReportsList;
  getDemandReportsByStatus = demandRepo.getDemandReportsByStatus;
  getDemandReportsByWorkflowStatus = demandRepo.getDemandReportsByWorkflowStatus;
  getDemandReportStats = demandRepo.getDemandReportStats;
  createDemandReport = demandRepo.createDemandReport;
  updateDemandReport = demandRepo.updateDemandReport;
  deleteDemandReport = demandRepo.deleteDemandReport;
  getDemandConversionRequest = demandRepo.getDemandConversionRequest;
  getDemandConversionRequestByDemandId = demandRepo.getDemandConversionRequestByDemandId;
  getAllDemandConversionRequests = demandRepo.getAllDemandConversionRequests;
  getDemandConversionRequestsByStatus = demandRepo.getDemandConversionRequestsByStatus;
  createDemandConversionRequest = demandRepo.createDemandConversionRequest;
  updateDemandConversionRequest = demandRepo.updateDemandConversionRequest;
  deleteDemandConversionRequest = demandRepo.deleteDemandConversionRequest;
  getBusinessCase = demandRepo.getBusinessCase;
  getBusinessCaseByDemandReportId = demandRepo.getBusinessCaseByDemandReportId;
  getAllBusinessCases = demandRepo.getAllBusinessCases;
  getBusinessCasesByStatus = demandRepo.getBusinessCasesByStatus;
  createBusinessCase = demandRepo.createBusinessCase;
  updateBusinessCase = demandRepo.updateBusinessCase;
  deleteBusinessCase = demandRepo.deleteBusinessCase;
  createTeam = demandRepo.createTeam;
  getTeam = demandRepo.getTeam;
  getTeams = demandRepo.getTeams;
  updateTeam = demandRepo.updateTeam;
  deleteTeam = demandRepo.deleteTeam;
  addTeamMember = demandRepo.addTeamMember;
  getTeamMembers = demandRepo.getTeamMembers;
  removeTeamMember = demandRepo.removeTeamMember;
  getUserTeams = demandRepo.getUserTeams;
  assignSection = demandRepo.assignSection;
  getSectionAssignments = demandRepo.getSectionAssignments;
  getSectionAssignment = demandRepo.getSectionAssignment;
  updateSectionAssignment = demandRepo.updateSectionAssignment;
  updateSectionAssignmentStatus = demandRepo.updateSectionAssignmentStatus;
  removeSectionAssignment = demandRepo.removeSectionAssignment;
  getUserAssignedSections = demandRepo.getUserAssignedSections;
  getUserAssignedSectionsWithStatus = demandRepo.getUserAssignedSectionsWithStatus;

  // ===== VERSIONING =====
  createReportVersion = versioningRepo.createReportVersion;
  getReportVersion = versioningRepo.getReportVersion;
  updateReportVersion = versioningRepo.updateReportVersion;
  deleteReportVersion = versioningRepo.deleteReportVersion;
  getReportVersions = versioningRepo.getReportVersions;
  getReportVersionsByStatus = versioningRepo.getReportVersionsByStatus;
  getLatestReportVersion = versioningRepo.getLatestReportVersion;
  getLatestReportVersionByType = versioningRepo.getLatestReportVersionByType;
  getPublishedReportVersions = versioningRepo.getPublishedReportVersions;
  getRequirementsStatuses = versioningRepo.getRequirementsStatuses;
  getEnterpriseArchitectureStatuses = versioningRepo.getEnterpriseArchitectureStatuses;
  getVersionsByMajor = versioningRepo.getVersionsByMajor;
  getVersionsByPattern = versioningRepo.getVersionsByPattern;
  getChildVersions = versioningRepo.getChildVersions;
  getVersionHierarchy = versioningRepo.getVersionHierarchy;
  createVersionAuditLog = versioningRepo.createVersionAuditLog;
  getVersionAuditLog = versioningRepo.getVersionAuditLog;
  getReportAuditLog = versioningRepo.getReportAuditLog;
  getAuditLogByUser = versioningRepo.getAuditLogByUser;
  getAuditLogByAction = versioningRepo.getAuditLogByAction;
  getAuditLogByDateRange = versioningRepo.getAuditLogByDateRange;
  executeInTransaction = versioningRepo.executeInTransaction;
  validateVersionIntegrity = versioningRepo.validateVersionIntegrity;
  recalculateVersionHash = versioningRepo.recalculateVersionHash;
  getVersionsForRetentionReview = versioningRepo.getVersionsForRetentionReview;
  archiveExpiredVersions = versioningRepo.archiveExpiredVersions;
  getComplianceReport = versioningRepo.getComplianceReport;
  createBranch = versioningRepo.createBranch;
  getBranches = versioningRepo.getBranches;
  getBranch = versioningRepo.getBranch;
  updateBranch = versioningRepo.updateBranch;
  deleteBranch = versioningRepo.deleteBranch;
  getBranchTree = versioningRepo.getBranchTree;
  createMerge = versioningRepo.createMerge;
  getMerges = versioningRepo.getMerges;
  getMerge = versioningRepo.getMerge;
  updateMerge = versioningRepo.updateMerge;

  // ===== KNOWLEDGE =====
  createKnowledgeDocument = knowledgeRepo.createKnowledgeDocument;
  getKnowledgeDocument = knowledgeRepo.getKnowledgeDocument;
  getKnowledgeDocuments = knowledgeRepo.getKnowledgeDocuments;
  listKnowledgeDocuments = knowledgeRepo.listKnowledgeDocuments;
  updateKnowledgeDocument = knowledgeRepo.updateKnowledgeDocument;
  deleteKnowledgeDocument = knowledgeRepo.deleteKnowledgeDocument;
  createKnowledgeChunk = knowledgeRepo.createKnowledgeChunk;
  createKnowledgeChunksBatch = knowledgeRepo.createKnowledgeChunksBatch;
  getKnowledgeChunksByDocument = knowledgeRepo.getKnowledgeChunksByDocument;
  deleteKnowledgeChunksByDocument = knowledgeRepo.deleteKnowledgeChunksByDocument;
  updateDocumentChunkEmbedding = knowledgeRepo.updateDocumentChunkEmbedding;
  searchKnowledgeChunks = knowledgeRepo.searchKnowledgeChunks;
  keywordSearchChunks = knowledgeRepo.keywordSearchChunks;
  logKnowledgeQuery = knowledgeRepo.logKnowledgeQuery;
  incrementChunkRetrievalCount = knowledgeRepo.incrementChunkRetrievalCount;

  // ===== COMPLIANCE =====
  createComplianceRule = complianceRepo.createComplianceRule;
  getComplianceRule = complianceRepo.getComplianceRule;
  getPublishedComplianceRules = complianceRepo.getPublishedComplianceRules;
  getComplianceRulesByCategory = complianceRepo.getComplianceRulesByCategory;
  updateComplianceRule = complianceRepo.updateComplianceRule;
  createComplianceRun = complianceRepo.createComplianceRun;
  getComplianceRun = complianceRepo.getComplianceRun;
  getComplianceRunsByReport = complianceRepo.getComplianceRunsByReport;
  getLatestComplianceRun = complianceRepo.getLatestComplianceRun;
  updateComplianceRun = complianceRepo.updateComplianceRun;
  createComplianceViolation = complianceRepo.createComplianceViolation;
  getComplianceViolation = complianceRepo.getComplianceViolation;
  getViolationsByRun = complianceRepo.getViolationsByRun;
  updateComplianceViolation = complianceRepo.updateComplianceViolation;

  // ===== INTELLIGENCE =====
  createOrchestrationRun = intelligenceRepo.createOrchestrationRun;
  getOrchestrationRun = intelligenceRepo.getOrchestrationRun;
  getOrchestrationRunsByUser = intelligenceRepo.getOrchestrationRunsByUser;
  getOrchestrationRunsByReport = intelligenceRepo.getOrchestrationRunsByReport;
  createSynergyOpportunity = intelligenceRepo.createSynergyOpportunity;
  getSynergyOpportunity = intelligenceRepo.getSynergyOpportunity;
  getAllSynergyOpportunities = intelligenceRepo.getAllSynergyOpportunities;
  getSynergyOpportunitiesByStatus = intelligenceRepo.getSynergyOpportunitiesByStatus;
  updateSynergyOpportunity = intelligenceRepo.updateSynergyOpportunity;
  getInnovationTemplates = intelligenceRepo.getInnovationTemplates;
  getInnovationTemplateById = intelligenceRepo.getInnovationTemplateById;
  searchInnovationTemplates = intelligenceRepo.searchInnovationTemplates;
  createInnovationTemplate = intelligenceRepo.createInnovationTemplate;
  getInnovationRecommendations = intelligenceRepo.getInnovationRecommendations;
  createInnovationRecommendation = intelligenceRepo.createInnovationRecommendation;
  createPortfolioRun = intelligenceRepo.createPortfolioRun;
  getPortfolioRuns = intelligenceRepo.getPortfolioRuns;
  getPortfolioRunById = intelligenceRepo.getPortfolioRunById;
  updatePortfolioRun = intelligenceRepo.updatePortfolioRun;
  createPortfolioRecommendation = intelligenceRepo.createPortfolioRecommendation;
  getPortfolioRecommendations = intelligenceRepo.getPortfolioRecommendations;
  updatePortfolioRecommendation = intelligenceRepo.updatePortfolioRecommendation;
  createTenderPackage = intelligenceRepo.createTenderPackage;
  getTenderPackages = intelligenceRepo.getTenderPackages;
  getTenderPackageById = intelligenceRepo.getTenderPackageById;
  getTenderPackagesByDemandId = intelligenceRepo.getTenderPackagesByDemandId;
  updateTenderPackage = intelligenceRepo.updateTenderPackage;
  createAgentFeedback = intelligenceRepo.createAgentFeedback;
  getAgentFeedback = intelligenceRepo.getAgentFeedback;
  getAgentFeedbackByDomain = intelligenceRepo.getAgentFeedbackByDomain;
  getAgentFeedbackByUser = intelligenceRepo.getAgentFeedbackByUser;
  getAgentFeedbackByReport = intelligenceRepo.getAgentFeedbackByReport;
  getTenderSlaRules = intelligenceRepo.getTenderSlaRules;
  getTenderSlaRuleById = intelligenceRepo.getTenderSlaRuleById;
  getTenderSlaRuleByType = intelligenceRepo.getTenderSlaRuleByType;
  createTenderSlaRule = intelligenceRepo.createTenderSlaRule;
  updateTenderSlaRule = intelligenceRepo.updateTenderSlaRule;
  getTenderSlaAssignment = intelligenceRepo.getTenderSlaAssignment;
  getSlaAssignmentsByStatus = intelligenceRepo.getSlaAssignmentsByStatus;
  createTenderSlaAssignment = intelligenceRepo.createTenderSlaAssignment;
  updateTenderSlaAssignment = intelligenceRepo.updateTenderSlaAssignment;
  getTenderNotifications = intelligenceRepo.getTenderNotifications;
  getNotificationsByRole = intelligenceRepo.getNotificationsByRole;
  createTenderNotification = intelligenceRepo.createTenderNotification;
  markNotificationRead = intelligenceRepo.markNotificationRead;
  markAllNotificationsRead = intelligenceRepo.markAllNotificationsRead;
  getTenderAlerts = intelligenceRepo.getTenderAlerts;
  createTenderAlert = intelligenceRepo.createTenderAlert;
  updateTenderAlert = intelligenceRepo.updateTenderAlert;
  resolveTenderAlert = intelligenceRepo.resolveTenderAlert;
  getTenderSlaMetrics = intelligenceRepo.getTenderSlaMetrics;
  getUpcomingDeadlines = intelligenceRepo.getUpcomingDeadlines;
  createRfpDocumentVersion = intelligenceRepo.createRfpDocumentVersion;
  getRfpDocumentVersion = intelligenceRepo.getRfpDocumentVersion;
  getRfpDocumentVersions = intelligenceRepo.getRfpDocumentVersions;
  getLatestRfpDocumentVersion = intelligenceRepo.getLatestRfpDocumentVersion;
  updateRfpDocumentVersion = intelligenceRepo.updateRfpDocumentVersion;
  deleteRfpDocumentVersion = intelligenceRepo.deleteRfpDocumentVersion;

  // ===== PORTFOLIO =====
  createPortfolioProject = portfolioRepo.createPortfolioProject;
  getPortfolioProject = portfolioRepo.getPortfolioProject;
  getPortfolioProjectByCode = portfolioRepo.getPortfolioProjectByCode;
  getPortfolioProjectByDemand = portfolioRepo.getPortfolioProjectByDemand;
  getAllPortfolioProjects = portfolioRepo.getAllPortfolioProjects;
  getPortfolioProjectsByPhase = portfolioRepo.getPortfolioProjectsByPhase;
  getPortfolioProjectsByStatus = portfolioRepo.getPortfolioProjectsByStatus;
  getPortfolioProjectsByManager = portfolioRepo.getPortfolioProjectsByManager;
  updatePortfolioProject = portfolioRepo.updatePortfolioProject;
  deletePortfolioProject = portfolioRepo.deletePortfolioProject;
  getPortfolioSummary = portfolioRepo.getPortfolioSummary;
  createProjectPhase = portfolioRepo.createProjectPhase;
  getProjectPhases = portfolioRepo.getProjectPhases;
  getProjectPhase = portfolioRepo.getProjectPhase;
  updateProjectPhase = portfolioRepo.updateProjectPhase;
  createProjectMilestone = portfolioRepo.createProjectMilestone;
  getProjectMilestones = portfolioRepo.getProjectMilestones;
  getProjectMilestone = portfolioRepo.getProjectMilestone;
  updateProjectMilestone = portfolioRepo.updateProjectMilestone;
  deleteProjectMilestone = portfolioRepo.deleteProjectMilestone;
  getUpcomingMilestones = portfolioRepo.getUpcomingMilestones;
  createProjectKpi = portfolioRepo.createProjectKpi;
  getProjectKpis = portfolioRepo.getProjectKpis;
  getProjectKpi = portfolioRepo.getProjectKpi;
  updateProjectKpi = portfolioRepo.updateProjectKpi;
  getKpisByCategory = portfolioRepo.getKpisByCategory;
  createPhaseHistory = portfolioRepo.createPhaseHistory;
  getPhaseHistory = portfolioRepo.getPhaseHistory;
  transitionProjectPhase = portfolioRepo.transitionProjectPhase;
  getProjectGates = portfolioRepo.getProjectGates;
  getAllPendingGates = portfolioRepo.getAllPendingGates;
  createProjectGate = portfolioRepo.createProjectGate;
  updateProjectGate = portfolioRepo.updateProjectGate;
  deleteProjectGate = portfolioRepo.deleteProjectGate;
  getProjectApprovals = portfolioRepo.getProjectApprovals;
  createProjectApproval = portfolioRepo.createProjectApproval;
  updateProjectApproval = portfolioRepo.updateProjectApproval;
  getPendingApprovals = portfolioRepo.getPendingApprovals;
  getProjectRisks = portfolioRepo.getProjectRisks;
  getProjectRisk = portfolioRepo.getProjectRisk;
  createProjectRisk = portfolioRepo.createProjectRisk;
  updateProjectRisk = portfolioRepo.updateProjectRisk;
  deleteProjectRisk = portfolioRepo.deleteProjectRisk;
  getRiskEvidence = portfolioRepo.getRiskEvidence;
  getRiskEvidenceById = portfolioRepo.getRiskEvidenceById;
  createRiskEvidence = portfolioRepo.createRiskEvidence;
  updateRiskEvidence = portfolioRepo.updateRiskEvidence;
  deleteRiskEvidence = portfolioRepo.deleteRiskEvidence;
  getProjectIssues = portfolioRepo.getProjectIssues;
  getProjectIssue = portfolioRepo.getProjectIssue;
  createProjectIssue = portfolioRepo.createProjectIssue;
  updateProjectIssue = portfolioRepo.updateProjectIssue;
  deleteProjectIssue = portfolioRepo.deleteProjectIssue;
  getWbsTasks = portfolioRepo.getWbsTasks;
  createWbsTask = portfolioRepo.createWbsTask;
  updateWbsTask = portfolioRepo.updateWbsTask;
  deleteWbsTask = portfolioRepo.deleteWbsTask;

  // Agile Workspace (Project Accelerator)
  getAgileSprints = portfolioRepo.getAgileSprints;
  createAgileSprint = portfolioRepo.createAgileSprint;
  updateAgileSprint = portfolioRepo.updateAgileSprint;
  deleteAgileSprint = portfolioRepo.deleteAgileSprint;

  getAgileEpics = portfolioRepo.getAgileEpics;
  createAgileEpic = portfolioRepo.createAgileEpic;
  updateAgileEpic = portfolioRepo.updateAgileEpic;
  deleteAgileEpic = portfolioRepo.deleteAgileEpic;

  getAgileWorkItems = portfolioRepo.getAgileWorkItems;
  getAgileWorkItem = portfolioRepo.getAgileWorkItem;
  createAgileWorkItem = portfolioRepo.createAgileWorkItem;
  updateAgileWorkItem = portfolioRepo.updateAgileWorkItem;
  deleteAgileWorkItem = portfolioRepo.deleteAgileWorkItem;

  getAgileWorkItemComments = portfolioRepo.getAgileWorkItemComments;
  createAgileWorkItemComment = portfolioRepo.createAgileWorkItemComment;

  getAgileProjectMembers = portfolioRepo.getAgileProjectMembers;
  upsertAgileProjectMember = portfolioRepo.upsertAgileProjectMember;
  updateAgileProjectMember = portfolioRepo.updateAgileProjectMember;
  deleteAgileProjectMember = portfolioRepo.deleteAgileProjectMember;
  getWbsApproval = portfolioRepo.getWbsApproval;
  getWbsApprovalHistory = portfolioRepo.getWbsApprovalHistory;
  getPendingWbsApprovals = portfolioRepo.getPendingWbsApprovals;
  createWbsApproval = portfolioRepo.createWbsApproval;
  updateWbsApproval = portfolioRepo.updateWbsApproval;
  supersedePendingWbsApprovals = portfolioRepo.supersedePendingWbsApprovals;
  getWbsVersions = portfolioRepo.getWbsVersions;
  getWbsVersion = portfolioRepo.getWbsVersion;
  getWbsVersionsByStatus = portfolioRepo.getWbsVersionsByStatus;
  getLatestWbsVersion = portfolioRepo.getLatestWbsVersion;
  createWbsVersion = portfolioRepo.createWbsVersion;
  updateWbsVersion = portfolioRepo.updateWbsVersion;
  getProjectStakeholders = portfolioRepo.getProjectStakeholders;
  createProjectStakeholder = portfolioRepo.createProjectStakeholder;
  updateProjectStakeholder = portfolioRepo.updateProjectStakeholder;
  deleteProjectStakeholder = portfolioRepo.deleteProjectStakeholder;
  getProjectCommunications = portfolioRepo.getProjectCommunications;
  createProjectCommunication = portfolioRepo.createProjectCommunication;
  updateProjectCommunication = portfolioRepo.updateProjectCommunication;
  deleteProjectCommunication = portfolioRepo.deleteProjectCommunication;
  getProjectCostEntries = portfolioRepo.getProjectCostEntries;
  createCostEntry = portfolioRepo.createCostEntry;
  updateCostEntry = portfolioRepo.updateCostEntry;
  deleteCostEntry = portfolioRepo.deleteCostEntry;
  getProjectProcurementItems = portfolioRepo.getProjectProcurementItems;
  createProcurementItem = portfolioRepo.createProcurementItem;
  updateProcurementItem = portfolioRepo.updateProcurementItem;
  deleteProcurementItem = portfolioRepo.deleteProcurementItem;
  getProjectPayments = portfolioRepo.getProjectPayments;
  getProcurementItemPayments = portfolioRepo.getProcurementItemPayments;
  createProcurementPayment = portfolioRepo.createProcurementPayment;
  updateProcurementPayment = portfolioRepo.updateProcurementPayment;
  deleteProcurementPayment = portfolioRepo.deleteProcurementPayment;
  updateWbsTaskActualCost = portfolioRepo.updateWbsTaskActualCost;
  getProjectDocuments = portfolioRepo.getProjectDocuments;
  createProjectDocument = portfolioRepo.createProjectDocument;
  updateProjectDocument = portfolioRepo.updateProjectDocument;
  deleteProjectDocument = portfolioRepo.deleteProjectDocument;
  getProjectChangeRequests = portfolioRepo.getProjectChangeRequests;
  getProjectChangeRequest = portfolioRepo.getProjectChangeRequest;
  getChangeRequestsByStatus = portfolioRepo.getChangeRequestsByStatus;
  getPendingChangeRequests = portfolioRepo.getPendingChangeRequests;
  getAllChangeRequestsWithProjects = portfolioRepo.getAllChangeRequestsWithProjects;
  createProjectChangeRequest = portfolioRepo.createProjectChangeRequest;
  updateProjectChangeRequest = portfolioRepo.updateProjectChangeRequest;
  deleteProjectChangeRequest = portfolioRepo.deleteProjectChangeRequest;

  // ===== GOVERNANCE =====
  createVendorParticipant = governanceRepo.createVendorParticipant;
  getVendorParticipant = governanceRepo.getVendorParticipant;
  getVendorParticipantsByDemand = governanceRepo.getVendorParticipantsByDemand;
  updateVendorParticipant = governanceRepo.updateVendorParticipant;
  deleteVendorParticipant = governanceRepo.deleteVendorParticipant;
  createVendorProposal = governanceRepo.createVendorProposal;
  getVendorProposal = governanceRepo.getVendorProposal;
  getVendorProposalsByDemand = governanceRepo.getVendorProposalsByDemand;
  getVendorProposalsByVendor = governanceRepo.getVendorProposalsByVendor;
  updateVendorProposal = governanceRepo.updateVendorProposal;
  deleteVendorProposal = governanceRepo.deleteVendorProposal;
  createEvaluationCriteria = governanceRepo.createEvaluationCriteria;
  getEvaluationCriteria = governanceRepo.getEvaluationCriteria;
  getEvaluationCriteriaByDemand = governanceRepo.getEvaluationCriteriaByDemand;
  getDefaultEvaluationCriteria = governanceRepo.getDefaultEvaluationCriteria;
  updateEvaluationCriteria = governanceRepo.updateEvaluationCriteria;
  deleteEvaluationCriteria = governanceRepo.deleteEvaluationCriteria;
  createProposalScore = governanceRepo.createProposalScore;
  getProposalScore = governanceRepo.getProposalScore;
  getProposalScoresByProposal = governanceRepo.getProposalScoresByProposal;
  getProposalScoresByCriterion = governanceRepo.getProposalScoresByCriterion;
  updateProposalScore = governanceRepo.updateProposalScore;
  deleteProposalScore = governanceRepo.deleteProposalScore;
  createVendorEvaluation = governanceRepo.createVendorEvaluation;
  getVendorEvaluation = governanceRepo.getVendorEvaluation;
  getVendorEvaluationByDemand = governanceRepo.getVendorEvaluationByDemand;
  updateVendorEvaluation = governanceRepo.updateVendorEvaluation;

  // ===== PERFORMANCE =====
  getStrategy = performanceRepo.getStrategy;
  getAllStrategies = performanceRepo.getAllStrategies;
  createStrategy = performanceRepo.createStrategy;
  updateStrategy = performanceRepo.updateStrategy;
  deleteStrategy = performanceRepo.deleteStrategy;
  getStrategiesByStatus = performanceRepo.getStrategiesByStatus;
  getObjective = performanceRepo.getObjective;
  getObjectivesByStrategy = performanceRepo.getObjectivesByStrategy;
  createObjective = performanceRepo.createObjective;
  updateObjective = performanceRepo.updateObjective;
  deleteObjective = performanceRepo.deleteObjective;
  getObjectiveCascade = performanceRepo.getObjectiveCascade;
  getKeyResult = performanceRepo.getKeyResult;
  getKeyResultsByObjective = performanceRepo.getKeyResultsByObjective;
  createKeyResult = performanceRepo.createKeyResult;
  updateKeyResult = performanceRepo.updateKeyResult;
  deleteKeyResult = performanceRepo.deleteKeyResult;
  getKpiDefinition = performanceRepo.getKpiDefinition;
  getAllKpiDefinitions = performanceRepo.getAllKpiDefinitions;
  createKpiDefinition = performanceRepo.createKpiDefinition;
  updateKpiDefinition = performanceRepo.updateKpiDefinition;
  getKpiDefinitionsByCategory = performanceRepo.getKpiDefinitionsByCategory;
  getKpiInstance = performanceRepo.getKpiInstance;
  getKpiInstancesByDepartment = performanceRepo.getKpiInstancesByDepartment;
  createKpiInstance = performanceRepo.createKpiInstance;
  updateKpiInstance = performanceRepo.updateKpiInstance;
  getDashboard = performanceRepo.getDashboard;
  getUserDashboards = performanceRepo.getUserDashboards;
  createDashboard = performanceRepo.createDashboard;
  updateDashboard = performanceRepo.updateDashboard;
  deleteDashboard = performanceRepo.deleteDashboard;
  getWidget = performanceRepo.getWidget;
  getWidgetsByDashboard = performanceRepo.getWidgetsByDashboard;
  createWidget = performanceRepo.createWidget;
  updateWidget = performanceRepo.updateWidget;
  deleteWidget = performanceRepo.deleteWidget;
  getDepartment = performanceRepo.getDepartment;
  getAllDepartments = performanceRepo.getAllDepartments;
  createDepartment = performanceRepo.createDepartment;
  updateDepartment = performanceRepo.updateDepartment;
  getDepartmentScorecard = performanceRepo.getDepartmentScorecard;
  getInitiative = performanceRepo.getInitiative;
  getInitiativesByObjective = performanceRepo.getInitiativesByObjective;
  createInitiative = performanceRepo.createInitiative;
  updateInitiative = performanceRepo.updateInitiative;
  getCheckIn = performanceRepo.getCheckIn;
  getCheckInsByEntity = performanceRepo.getCheckInsByEntity;
  createCheckIn = performanceRepo.createCheckIn;
  getInsight = performanceRepo.getInsight;
  getInsightsByEntity = performanceRepo.getInsightsByEntity;
  createInsight = performanceRepo.createInsight;
  acknowledgeInsight = performanceRepo.acknowledgeInsight;

  // ===== LEARNING =====
  createLoraGoldExample = learningRepo.createLoraGoldExample;
  getLoraGoldExample = learningRepo.getLoraGoldExample;
  getLoraGoldExamplesBySectionType = learningRepo.getLoraGoldExamplesBySectionType;
  getLoraGoldExamplesByDataset = learningRepo.getLoraGoldExamplesByDataset;
  getLoraGoldExamplesAboveQuality = learningRepo.getLoraGoldExamplesAboveQuality;
  updateLoraGoldExample = learningRepo.updateLoraGoldExample;
  deleteLoraGoldExample = learningRepo.deleteLoraGoldExample;
  createLoraDataset = learningRepo.createLoraDataset;
  getLoraDataset = learningRepo.getLoraDataset;
  getAllLoraDatasets = learningRepo.getAllLoraDatasets;
  getLoraDatasetsByStatus = learningRepo.getLoraDatasetsByStatus;
  updateLoraDataset = learningRepo.updateLoraDataset;
  deleteLoraDataset = learningRepo.deleteLoraDataset;
  createLoraTrainingJob = learningRepo.createLoraTrainingJob;
  getLoraTrainingJob = learningRepo.getLoraTrainingJob;
  getLoraTrainingJobsByStatus = learningRepo.getLoraTrainingJobsByStatus;
  getLoraTrainingJobsByDataset = learningRepo.getLoraTrainingJobsByDataset;
  updateLoraTrainingJob = learningRepo.updateLoraTrainingJob;
  createLoraAdapter = learningRepo.createLoraAdapter;
  getLoraAdapter = learningRepo.getLoraAdapter;
  getLoraAdaptersByModel = learningRepo.getLoraAdaptersByModel;
  getActiveLoraAdapters = learningRepo.getActiveLoraAdapters;
  updateLoraAdapter = learningRepo.updateLoraAdapter;
  incrementLoraAdapterUsage = learningRepo.incrementLoraAdapterUsage;

  // ===== EA REGISTRY =====
  getEaApplication = eaRegistryRepo.getEaApplication;
  getAllEaApplications = eaRegistryRepo.getAllEaApplications;
  createEaApplication = eaRegistryRepo.createEaApplication;
  updateEaApplication = eaRegistryRepo.updateEaApplication;
  deleteEaApplication = eaRegistryRepo.deleteEaApplication;
  getEaCapability = eaRegistryRepo.getEaCapability;
  getAllEaCapabilities = eaRegistryRepo.getAllEaCapabilities;
  createEaCapability = eaRegistryRepo.createEaCapability;
  updateEaCapability = eaRegistryRepo.updateEaCapability;
  deleteEaCapability = eaRegistryRepo.deleteEaCapability;
  getEaDataDomain = eaRegistryRepo.getEaDataDomain;
  getAllEaDataDomains = eaRegistryRepo.getAllEaDataDomains;
  createEaDataDomain = eaRegistryRepo.createEaDataDomain;
  updateEaDataDomain = eaRegistryRepo.updateEaDataDomain;
  deleteEaDataDomain = eaRegistryRepo.deleteEaDataDomain;
  getEaTechnologyStandard = eaRegistryRepo.getEaTechnologyStandard;
  getAllEaTechnologyStandards = eaRegistryRepo.getAllEaTechnologyStandards;
  createEaTechnologyStandard = eaRegistryRepo.createEaTechnologyStandard;
  updateEaTechnologyStandard = eaRegistryRepo.updateEaTechnologyStandard;
  deleteEaTechnologyStandard = eaRegistryRepo.deleteEaTechnologyStandard;
  getEaIntegration = eaRegistryRepo.getEaIntegration;
  getAllEaIntegrations = eaRegistryRepo.getAllEaIntegrations;
  createEaIntegration = eaRegistryRepo.createEaIntegration;
  updateEaIntegration = eaRegistryRepo.updateEaIntegration;
  deleteEaIntegration = eaRegistryRepo.deleteEaIntegration;

}
