/**
 * COREVIA Notification Orchestrator
 * 
 * Single source of truth for all notification channels across the system.
 * Every service registers its channels here. Admins toggle channels on/off.
 * When a notification is emitted, the orchestrator checks:
 *   1. Is the channel globally enabled?
 *   2. Does the user have a preference override?
 *   3. What delivery methods are configured?
 * Then routes the notification to the correct tables/transports.
 */

import { db } from "@platform/db";
import { eq, and, sql } from "drizzle-orm";
import {
  notificationChannels,
  notificationChannelPreferences,
  type NotificationChannel,
} from "@shared/schemas/corevia/tables";
import { notifications, aiNotifications, users } from "@shared/schema";
import { whatsAppService } from "./whatsAppService";
import { sendEmail } from "@platform/notifications";
import { logger } from "@platform/logging/Logger";

// Simple HTML escape for email content
function escapeHtmlSimple(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

// ── Channel Definitions (auto-registered at startup) ───────────────────────

export interface ChannelDefinition {
  id: string;
  serviceName: string;
  category: string;
  name: string;
  description: string;
  priority?: string;
  icon?: string;
  deliveryMethods?: string[];
  config?: Record<string, unknown>;
}

const SYSTEM_CHANNELS: ChannelDefinition[] = [
  // ─── Demand Management ───
  {
    id: "demand.status_change",
    serviceName: "Demand Management",
    category: "demand",
    name: "Demand Status Change",
    description: "Notifies when a demand report status changes (e.g., submitted → under review → approved)",
    priority: "medium",
    icon: "Activity",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "demand.section_assigned",
    serviceName: "Demand Management",
    category: "demand",
    name: "Section Assignment",
    description: "Notifies users when they are assigned to a demand report section",
    priority: "high",
    icon: "Users",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "demand.team_assigned",
    serviceName: "Demand Management",
    category: "demand",
    name: "Team Member Assignment",
    description: "Notifies when a team member is added to a demand report",
    priority: "medium",
    icon: "Users",
    deliveryMethods: ["in_app"],
  },
  {
    id: "demand.mention",
    serviceName: "Demand Management",
    category: "demand",
    name: "Mentioned in Comment",
    description: "Notifies when a user is mentioned in a comment or discussion",
    priority: "medium",
    icon: "MessageSquare",
    deliveryMethods: ["in_app"],
  },
  // ─── AI / COREVIA Brain ───
  {
    id: "ai.insight",
    serviceName: "COREVIA Intelligence",
    category: "ai",
    name: "AI Insight",
    description: "AI-generated insights about patterns, anomalies, or recommendations",
    priority: "medium",
    icon: "Lightbulb",
    deliveryMethods: ["in_app"],
  },
  {
    id: "ai.proactive_alert",
    serviceName: "COREVIA Intelligence",
    category: "ai",
    name: "Proactive Alert",
    description: "Critical alerts auto-generated by anomaly detection (budget overruns, stalled items)",
    priority: "high",
    icon: "AlertTriangle",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "ai.suggestion",
    serviceName: "COREVIA Intelligence",
    category: "ai",
    name: "AI Suggestion",
    description: "Actionable suggestions from COREVIA AI to improve processes",
    priority: "low",
    icon: "Target",
    deliveryMethods: ["in_app"],
  },
  {
    id: "ai.daily_briefing",
    serviceName: "COREVIA Intelligence",
    category: "ai",
    name: "Daily Briefing",
    description: "Executive daily briefing summarizing system activity and pending actions",
    priority: "medium",
    icon: "Sparkles",
    deliveryMethods: ["in_app"],
    config: { briefingTime: "09:00" },
  },
  {
    id: "ai.brain_event",
    serviceName: "COREVIA Brain",
    category: "ai",
    name: "Brain Event",
    description: "Decision spine processing, attestation, and policy enforcement events",
    priority: "low",
    icon: "Brain",
    deliveryMethods: ["in_app"],
  },
  // ─── Tender / Procurement ───
  {
    id: "tender.status_update",
    serviceName: "Procurement",
    category: "tender",
    name: "Tender Status Update",
    description: "Notifies on tender lifecycle changes (draft → published → evaluation → awarded)",
    priority: "medium",
    icon: "Package",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "tender.sla_reminder",
    serviceName: "Procurement",
    category: "tender",
    name: "SLA Reminder",
    description: "Warning before an SLA deadline is approaching",
    priority: "high",
    icon: "Clock",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "tender.sla_breach",
    serviceName: "Procurement",
    category: "tender",
    name: "SLA Breach",
    description: "Critical alert when an SLA deadline has been missed",
    priority: "critical",
    icon: "AlertTriangle",
    deliveryMethods: ["in_app", "email", "whatsapp"],
  },
  {
    id: "tender.action_required",
    serviceName: "Procurement",
    category: "tender",
    name: "Action Required",
    description: "Tender requires immediate user action (evaluation, approval, etc.)",
    priority: "high",
    icon: "Zap",
    deliveryMethods: ["in_app", "email"],
  },
  // ─── Compliance & Governance ───
  {
    id: "compliance.policy_violation",
    serviceName: "Governance",
    category: "compliance",
    name: "Policy Violation",
    description: "Data sovereignty or governance policy was violated or blocked",
    priority: "critical",
    icon: "Shield",
    deliveryMethods: ["in_app", "email", "whatsapp"],
  },
  {
    id: "compliance.gate_check",
    serviceName: "Governance",
    category: "compliance",
    name: "Gate Check Result",
    description: "Gate checkpoint evaluation completed (pass/fail/conditional)",
    priority: "medium",
    icon: "CheckCircle2",
    deliveryMethods: ["in_app"],
  },
  // ─── System / Workflow ───
  {
    id: "system.approval_needed",
    serviceName: "Workflow",
    category: "system",
    name: "Approval Needed",
    description: "A workflow step requires your approval",
    priority: "high",
    icon: "Gavel",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "system.deadline",
    serviceName: "Workflow",
    category: "system",
    name: "Deadline Approaching",
    description: "Task or deliverable deadline is approaching",
    priority: "high",
    icon: "Clock",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "system.overdue",
    serviceName: "Workflow",
    category: "system",
    name: "Overdue Task",
    description: "A task or deliverable has passed its deadline",
    priority: "critical",
    icon: "AlertTriangle",
    deliveryMethods: ["in_app", "email", "whatsapp"],
  },
  {
    id: "system.meeting_request",
    serviceName: "Workflow",
    category: "system",
    name: "Meeting Request",
    description: "A meeting has been scheduled or requested",
    priority: "medium",
    icon: "Calendar",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "email.workflow",
    serviceName: "Email Service",
    category: "system",
    name: "Email Notifications",
    description: "SendGrid email delivery for workflow events (approvals, assignments, status changes)",
    priority: "medium",
    icon: "Mail",
    deliveryMethods: ["email"],
    config: { provider: "sendgrid" },
  },
  {
    id: "system.task_assigned",
    serviceName: "Workflow",
    category: "system",
    name: "Task Assigned",
    description: "A task has been assigned to you",
    priority: "medium",
    icon: "CheckCircle2",
    deliveryMethods: ["in_app"],
  },
  {
    id: "system.system_alert",
    serviceName: "Workflow",
    category: "system",
    name: "System Alert",
    description: "General system alert or important notification",
    priority: "high",
    icon: "AlertTriangle",
    deliveryMethods: ["in_app", "email"],
  },
  // ─── PMO / Portfolio ───
  {
    id: "pmo.project_assigned",
    serviceName: "Portfolio Management",
    category: "pmo",
    name: "Project Role Assignment",
    description: "Notifies when someone is assigned a project role (PM, Sponsor, Financial Director, Steering Committee)",
    priority: "high",
    icon: "Users",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "pmo.charter_signature_required",
    serviceName: "Portfolio Management",
    category: "pmo",
    name: "Charter Signature Required",
    description: "Project charter sent for digital signature — requires PM, Sponsor, and Financial Director signatures",
    priority: "critical",
    icon: "Gavel",
    deliveryMethods: ["in_app", "email", "whatsapp"],
  },
  {
    id: "pmo.charter_approved",
    serviceName: "Portfolio Management",
    category: "pmo",
    name: "Charter Approved",
    description: "All charter signatures collected and charter is now locked",
    priority: "high",
    icon: "CheckCircle2",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "pmo.charter_signature_reminder",
    serviceName: "Portfolio Management",
    category: "pmo",
    name: "Charter Signature Reminder",
    description: "Reminder to pending charter signatories who have not yet signed",
    priority: "high",
    icon: "Clock",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "pmo.wbs_approval",
    serviceName: "Portfolio Management",
    category: "pmo",
    name: "WBS Approval Request",
    description: "Work Breakdown Structure submitted for PMO review and approval",
    priority: "high",
    icon: "Gavel",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "pmo.demand_conversion",
    serviceName: "Portfolio Management",
    category: "pmo",
    name: "Demand-to-Project Conversion",
    description: "Demand approved for conversion to active project — requires PMO approval",
    priority: "high",
    icon: "ArrowRight",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "pmo.gate_approval",
    serviceName: "Portfolio Management",
    category: "pmo",
    name: "Gate Approval Request",
    description: "Project gate checkpoint submitted for PMO approval (G0–G5)",
    priority: "high",
    icon: "Shield",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "pmo.gate_decision",
    serviceName: "Portfolio Management",
    category: "pmo",
    name: "Gate Decision Notification",
    description: "Gate decision outcome notification — approved (phase advanced), rejected, or deferred",
    priority: "high",
    icon: "Activity",
    deliveryMethods: ["in_app", "email"],
  },
  // ─── Communications ───
  {
    id: "communications.plan_activated",
    serviceName: "Communications",
    category: "communications",
    name: "Communication Plan Activated",
    description: "Communication plan approved and activated — stakeholders subscribed to channels",
    priority: "medium",
    icon: "MessageSquare",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "communications.plan_approved",
    serviceName: "Communications",
    category: "communications",
    name: "Communication Plan Approved",
    description: "Communication plan formally approved with assigned channels and audiences",
    priority: "medium",
    icon: "CheckCircle2",
    deliveryMethods: ["in_app"],
  },
  {
    id: "communications.trigger_executed",
    serviceName: "Communications",
    category: "communications",
    name: "Auto-Trigger Executed",
    description: "Communication trigger fired automatically (milestone, status change, escalation, etc.)",
    priority: "medium",
    icon: "Zap",
    deliveryMethods: ["in_app"],
  },
  // ─── Risk & Budget ───
  {
    id: "risk.alert",
    serviceName: "Risk Management",
    category: "risk",
    name: "Risk Alert",
    description: "Project risk level elevated — schedule delays, resource conflicts, or scope changes detected",
    priority: "high",
    icon: "AlertTriangle",
    deliveryMethods: ["in_app", "email"],
  },
  {
    id: "risk.budget_warning",
    serviceName: "Risk Management",
    category: "risk",
    name: "Budget Warning",
    description: "Project expenditure has exceeded budget threshold (e.g., 80% or 100%)",
    priority: "high",
    icon: "TrendingUp",
    deliveryMethods: ["in_app", "email"],
  },
  // ─── Additional AI ───
  {
    id: "ai.coveria_alert",
    serviceName: "COREVIA Intelligence",
    category: "ai",
    name: "Coveria Action Alert",
    description: "COREVIA AI action executed — automated task, decision, or system operation",
    priority: "high",
    icon: "Bot",
    deliveryMethods: ["in_app"],
  },
  {
    id: "ai.workflow_event",
    serviceName: "COREVIA Intelligence",
    category: "ai",
    name: "AI Workflow Event",
    description: "AI-driven workflow triggered — document submitted, approval chain initiated, or review started",
    priority: "medium",
    icon: "Sparkles",
    deliveryMethods: ["in_app"],
  },
];

// ── Orchestrator Class ────────────────────────────────────────────────────

class NotificationOrchestrator {
  private channelCache: Map<string, NotificationChannel> = new Map();
  private initialized = false;

  /**
   * Register all system channels (idempotent — uses ON CONFLICT DO UPDATE).
   * Called once at server startup.
   */
  async initialize(): Promise<void> {
    if (this.initialized) return;

    try {
      for (const def of SYSTEM_CHANNELS) {
        await db
          .insert(notificationChannels)
          .values({
            id: def.id,
            serviceName: def.serviceName,
            category: def.category,
            name: def.name,
            description: def.description,
            priority: def.priority || "medium",
            icon: def.icon || null,
            deliveryMethods: def.deliveryMethods || ["in_app"],
            config: def.config || {},
          })
          .onConflictDoUpdate({
            target: notificationChannels.id,
            set: {
              serviceName: sql`EXCLUDED.service_name`,
              name: sql`EXCLUDED.name`,
              description: sql`EXCLUDED.description`,
              icon: sql`EXCLUDED.icon`,
              deliveryMethods: sql`EXCLUDED.delivery_methods`,
              priority: sql`EXCLUDED.priority`,
              updatedAt: sql`now()`,
            },
          });
      }

      // Warm cache
      await this.refreshCache();
      this.initialized = true;
      logger.info(`[NotificationOrchestrator] Registered ${SYSTEM_CHANNELS.length} channels`);
    } catch (error: unknown) {
      logger.error("[NotificationOrchestrator] Init failed:", (error as Error)?.message);
    }
  }

  /**
   * Refresh the in-memory channel cache from DB.
   */
  async refreshCache(): Promise<void> {
    const rows = await db.select().from(notificationChannels);
    this.channelCache.clear();
    for (const row of rows) {
      this.channelCache.set(row.id, row);
    }
  }

  /**
   * Get all registered channels.
   */
  async getChannels(): Promise<NotificationChannel[]> {
    if (this.channelCache.size === 0) await this.refreshCache();
    return Array.from(this.channelCache.values());
  }

  /**
   * Get channels grouped by category.
   */
  async getChannelsGrouped(): Promise<Record<string, NotificationChannel[]>> {
    const channels = await this.getChannels();
    const grouped: Record<string, NotificationChannel[]> = {};
    for (const ch of channels) {
      if (!grouped[ch.category]) grouped[ch.category] = [];
      grouped[ch.category]!.push(ch);
    }
    return grouped;
  }

  /**
   * Get a single channel by ID.
   */
  async getChannel(channelId: string): Promise<NotificationChannel | null> {
    if (this.channelCache.has(channelId)) return this.channelCache.get(channelId)!;
    const rows = await db.select().from(notificationChannels).where(eq(notificationChannels.id, channelId)).limit(1);
    if (rows.length > 0) {
      this.channelCache.set(rows[0]!.id, rows[0]!);
      return rows[0]!;
    }
    return null;
  }

  /**
   * Toggle a channel's global enabled state.
   */
  async toggleChannel(channelId: string, enabled: boolean): Promise<NotificationChannel | null> {
    const [updated] = await db
      .update(notificationChannels)
      .set({ enabled, updatedAt: new Date() })
      .where(eq(notificationChannels.id, channelId))
      .returning();
    if (updated) {
      this.channelCache.set(updated.id, updated);
    }
    return updated || null;
  }

  /**
   * Update a channel's configuration (delivery methods, priority, custom config).
   */
  async updateChannelConfig(
    channelId: string,
    updates: {
      deliveryMethods?: string[];
      priority?: string;
      config?: Record<string, unknown>;
    }
  ): Promise<NotificationChannel | null> {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const setClause: Record<string, any> = { updatedAt: new Date() };
    if (updates.deliveryMethods) setClause.deliveryMethods = updates.deliveryMethods;
    if (updates.priority) setClause.priority = updates.priority;
    if (updates.config) setClause.config = updates.config;

    const [updated] = await db
      .update(notificationChannels)
      .set(setClause)
      .where(eq(notificationChannels.id, channelId))
      .returning();
    if (updated) {
      this.channelCache.set(updated.id, updated);
    }
    return updated || null;
  }

  /**
   * Register a custom channel (e.g., from a plugin or external integration).
   */
  async registerChannel(def: ChannelDefinition): Promise<NotificationChannel> {
    const [row] = await db
      .insert(notificationChannels)
      .values({
        id: def.id,
        serviceName: def.serviceName,
        category: def.category,
        name: def.name,
        description: def.description,
        priority: def.priority || "medium",
        icon: def.icon || null,
        deliveryMethods: def.deliveryMethods || ["in_app"],
        config: def.config || {},
      })
      .onConflictDoUpdate({
        target: notificationChannels.id,
        set: {
          serviceName: sql`EXCLUDED.service_name`,
          name: sql`EXCLUDED.name`,
          description: sql`EXCLUDED.description`,
          updatedAt: sql`now()`,
        },
      })
      .returning();
    this.channelCache.set(row!.id, row!);
    return row!;
  }

  /**
   * Get per-user preferences for all channels.
   */
  async getUserPreferences(userId: string) {
    return db
      .select()
      .from(notificationChannelPreferences)
      .where(eq(notificationChannelPreferences.userId, userId));
  }

  /**
   * Set a user's preference for a specific channel.
   */
  async setUserPreference(
    userId: string,
    channelId: string,
    prefs: { enabled?: boolean; deliveryMethods?: string[]; config?: Record<string, unknown> }
  ) {
    // Upsert
    const existing = await db
      .select()
      .from(notificationChannelPreferences)
      .where(
        and(
          eq(notificationChannelPreferences.userId, userId),
          eq(notificationChannelPreferences.channelId, channelId)
        )
      )
      .limit(1);

    if (existing.length > 0) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const setClause: Record<string, any> = { updatedAt: new Date() };
      if (prefs.enabled !== undefined) setClause.enabled = prefs.enabled;
      if (prefs.deliveryMethods) setClause.deliveryMethods = prefs.deliveryMethods;
      if (prefs.config) setClause.config = prefs.config;

      await db
        .update(notificationChannelPreferences)
        .set(setClause)
        .where(eq(notificationChannelPreferences.id, existing[0]!.id));
    } else {
      await db.insert(notificationChannelPreferences).values({
        userId,
        channelId,
        enabled: prefs.enabled ?? true,
        deliveryMethods: prefs.deliveryMethods ?? null,
        config: prefs.config ?? null,
      });
    }
  }

  /**
   * Check if a channel is enabled for a specific user.
   * Checks: global channel state → user override.
   */
  async isEnabledForUser(channelId: string, userId: string): Promise<boolean> {
    const channel = await this.getChannel(channelId);
    if (!channel || !channel.enabled) return false; // globally disabled

    const prefs = await db
      .select()
      .from(notificationChannelPreferences)
      .where(
        and(
          eq(notificationChannelPreferences.userId, userId),
          eq(notificationChannelPreferences.channelId, channelId)
        )
      )
      .limit(1);

    if (prefs.length > 0) return prefs[0]!.enabled;
    return true; // default: enabled if channel is globally enabled
  }

  /**
   * Emit a notification through a channel.
   * Routes to the appropriate table based on channel category.
   */
  async emit(params: {
    channelId: string;
    userId: string;
    title: string;
    message: string;
    priority?: string;
    relatedType?: string;
    relatedId?: string;
    actionUrl?: string;
    metadata?: Record<string, unknown>;
  }): Promise<boolean> {
    const enabled = await this.isEnabledForUser(params.channelId, params.userId);
    if (!enabled) return false;

    const channel = await this.getChannel(params.channelId);
    if (!channel) return false;

    // Resolve effective delivery methods (user prefs override channel defaults)
    const userPrefs = await this.getUserPreferences(params.userId);
    const channelPref = userPrefs.find((p: Record<string, unknown>) => p.channelId === params.channelId);
    const deliveryMethods: string[] = (channelPref?.deliveryMethods as string[] | undefined) ?? (channel.deliveryMethods as string[] | undefined) ?? ["in_app"];

    // ── 1. In-App: always write to DB notification tables ──
    if (deliveryMethods.includes("in_app") || deliveryMethods.includes("websocket")) {
      const category = channel.category;
      if (category === "ai" || category === "compliance") {
        await db.insert(aiNotifications).values({
          userId: params.userId,
          title: params.title,
          message: params.message,
          type: params.channelId.split(".").pop() || "alert",
          priority: params.priority || channel.priority,
          relatedType: params.relatedType,
          relatedId: params.relatedId,
          actionUrl: params.actionUrl,
        });
      } else {
        await db.insert(notifications).values({
          userId: params.userId,
          type: params.channelId.split(".").pop() || "general",
          title: params.title,
          message: params.message,
          metadata: params.metadata ? JSON.stringify(params.metadata) : undefined,
        });
      }
    }

    // ── 2. Email delivery ──
    if (deliveryMethods.includes("email")) {
      try {
        const [user] = await db.select({ email: users.email, displayName: users.displayName })
          .from(users).where(eq(users.id, params.userId)).limit(1);
        if (user?.email) {
          const fromEmail = process.env.NOTIFICATION_FROM_EMAIL || process.env.SENDGRID_FROM_EMAIL || "noreply@corevia.ae";
          await sendEmail({
            to: user.email,
            from: fromEmail,
            subject: `[COREVIA] ${params.title}`,
            html: `
              <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
                <div style="background:#7c3aed;padding:16px 24px;border-radius:8px 8px 0 0">
                  <h2 style="color:#fff;margin:0;font-size:16px">🔔 ${escapeHtmlSimple(params.title)}</h2>
                </div>
                <div style="padding:24px;border:1px solid #e5e7eb;border-top:0;border-radius:0 0 8px 8px">
                  <p style="color:#374151;line-height:1.6;margin:0 0 16px">${escapeHtmlSimple(params.message)}</p>
                  <p style="color:#9ca3af;font-size:12px;margin:0">Priority: <strong>${(params.priority || channel.priority || "medium").toUpperCase()}</strong> · Channel: ${channel.name}</p>
                  ${params.actionUrl ? `<p style="margin:16px 0 0"><a href="${params.actionUrl}" style="background:#7c3aed;color:#fff;padding:8px 20px;border-radius:6px;text-decoration:none;font-size:14px">View Details</a></p>` : ""}
                </div>
                <p style="color:#9ca3af;font-size:11px;text-align:center;margin:12px 0 0">COREVIA Brain — Intelligent IT Governance</p>
              </div>
            `,
            text: `${params.title}\n\n${params.message}\n\nPriority: ${(params.priority || "medium").toUpperCase()}`,
          });
        }
      } catch (emailErr: unknown) {
        logger.error(`[NotificationOrchestrator] Email delivery failed for ${params.channelId}:`, (emailErr as Error)?.message);
      }
    }

    // ── 3. WhatsApp delivery ──
    if (deliveryMethods.includes("whatsapp") && whatsAppService.isAvailable()) {
      try {
        const [user] = await db.select({ phoneNumber: users.phoneNumber, whatsappOptIn: users.whatsappOptIn, displayName: users.displayName })
          .from(users).where(eq(users.id, params.userId)).limit(1);
        if (user?.phoneNumber && user?.whatsappOptIn) {
          await whatsAppService.sendNotification({
            to: user.phoneNumber,
            title: params.title,
            message: params.message,
            priority: params.priority || channel.priority,
            channelName: channel.name,
            actionUrl: params.actionUrl,
          });
        }
      } catch (waErr: unknown) {
        logger.error(`[NotificationOrchestrator] WhatsApp delivery failed for ${params.channelId}:`, (waErr as Error)?.message);
      }
    }

    return true;
  }

  /**
   * Get notification stats per channel (counts from the last 24h, 7d, 30d).
   */
  async getChannelStats(): Promise<Record<string, { total24h: number; total7d: number; total30d: number }>> {
    const stats: Record<string, { total24h: number; total7d: number; total30d: number }> = {};

    // Get counts from notifications table (system/demand channels)
    const systemCounts = await db.execute(sql`
      SELECT type,
        COUNT(*) FILTER (WHERE created_at > now() - interval '24 hours') as count_24h,
        COUNT(*) FILTER (WHERE created_at > now() - interval '7 days') as count_7d,
        COUNT(*) FILTER (WHERE created_at > now() - interval '30 days') as count_30d
      FROM notifications
      GROUP BY type
    `);

    for (const row of systemCounts.rows as Record<string, any>[]) { // eslint-disable-line @typescript-eslint/no-explicit-any
      const channelId = `demand.${row.type}` in Object.fromEntries(this.channelCache)
        ? `demand.${row.type}`
        : `system.${row.type}`;
      stats[channelId] = {
        total24h: parseInt(row.count_24h) || 0,
        total7d: parseInt(row.count_7d) || 0,
        total30d: parseInt(row.count_30d) || 0,
      };
    }

    // Get counts from ai_notifications table
    const aiCounts = await db.execute(sql`
      SELECT type,
        COUNT(*) FILTER (WHERE created_at > now() - interval '24 hours') as count_24h,
        COUNT(*) FILTER (WHERE created_at > now() - interval '7 days') as count_7d,
        COUNT(*) FILTER (WHERE created_at > now() - interval '30 days') as count_30d
      FROM ai_notifications
      GROUP BY type
    `);

    for (const row of aiCounts.rows as Record<string, any>[]) { // eslint-disable-line @typescript-eslint/no-explicit-any
      stats[`ai.${row.type}`] = {
        total24h: parseInt(row.count_24h) || 0,
        total7d: parseInt(row.count_7d) || 0,
        total30d: parseInt(row.count_30d) || 0,
      };
    }

    return stats;
  }
}

// Singleton
export const notificationOrchestrator = new NotificationOrchestrator();
