import { 
  FileText, 
  Eye, 
  Brain, 
  Calendar, 
  CheckCircle, 
  Clock, 
  Shield, 
  ArrowRightCircle, 
  CheckCircle2 
} from "lucide-react";

export interface WorkflowStage {
  id: string;
  label: string;
  icon: typeof FileText;
  description: string;
  color: string;
  gradient: string;
}

export function getWorkflowStages(): WorkflowStage[] {
  return [
    { 
      id: 'generated', 
      label: 'Generated', 
      icon: FileText, 
      description: 'Report generated by AI',
      color: 'bg-gray-500/10 border-gray-500/20 text-gray-700 dark:text-gray-300',
      gradient: 'from-gray-500/5 to-gray-600/5'
    },
    { 
      id: 'acknowledged', 
      label: 'Acknowledged', 
      icon: Eye, 
      description: 'Request acknowledged by team',
      color: 'bg-blue-500/10 border-blue-500/20 text-blue-700 dark:text-blue-300',
      gradient: 'from-blue-500/5 to-blue-600/5'
    },
    { 
      id: 'under_review', 
      label: 'Under Review', 
      icon: Brain, 
      description: 'Currently being analyzed',
      color: 'bg-yellow-500/10 border-yellow-500/20 text-yellow-700 dark:text-yellow-300',
      gradient: 'from-yellow-500/5 to-yellow-600/5'
    },
    { 
      id: 'meeting_scheduled', 
      label: 'Meeting Scheduled', 
      icon: Calendar, 
      description: 'Stakeholder meeting planned',
      color: 'bg-purple-500/10 border-purple-500/20 text-purple-700 dark:text-purple-300',
      gradient: 'from-purple-500/5 to-purple-600/5'
    },
    { 
      id: 'initially_approved', 
      label: 'Initial Approval', 
      icon: CheckCircle, 
      description: 'Initially approved by reviewer',
      color: 'bg-emerald-500/10 border-emerald-500/20 text-emerald-700 dark:text-emerald-300',
      gradient: 'from-emerald-500/5 to-emerald-600/5'
    },
    { 
      id: 'manager_approval', 
      label: 'Pending Final Approval', 
      icon: Clock, 
      description: 'Awaiting director final approval',
      color: 'bg-amber-500/10 border-amber-500/20 text-amber-700 dark:text-amber-300',
      gradient: 'from-amber-500/5 to-amber-600/5'
    },
    { 
      id: 'manager_approved', 
      label: 'Approved', 
      icon: Shield, 
      description: 'Final approval obtained',
      color: 'bg-green-500/10 border-green-500/20 text-green-700 dark:text-green-300',
      gradient: 'from-green-500/5 to-green-600/5'
    },
    { 
      id: 'pending_conversion', 
      label: 'Pending Conversion', 
      icon: ArrowRightCircle, 
      description: 'Awaiting PMO approval for project conversion',
      color: 'bg-indigo-500/10 border-indigo-500/20 text-indigo-700 dark:text-indigo-300',
      gradient: 'from-indigo-500/5 to-indigo-600/5'
    },
    { 
      id: 'converted', 
      label: 'Converted', 
      icon: CheckCircle2, 
      description: 'Successfully converted to project',
      color: 'bg-teal-500/10 border-teal-500/20 text-teal-700 dark:text-teal-300',
      gradient: 'from-teal-500/5 to-teal-600/5'
    }
  ];
}

export function getWorkflowStatusColor(status: string | null | undefined): string {
  const statusColors: Record<string, string> = {
    generated: 'bg-gray-500/10 text-gray-700 border-gray-200 dark:text-gray-300 dark:border-gray-700',
    acknowledged: 'bg-blue-500/10 text-blue-700 border-blue-200 dark:text-blue-300 dark:border-blue-700',
    under_review: 'bg-yellow-500/10 text-yellow-700 border-yellow-200 dark:text-yellow-300 dark:border-yellow-700',
    meeting_scheduled: 'bg-purple-500/10 text-purple-700 border-purple-200 dark:text-purple-300 dark:border-purple-700',
    initially_approved: 'bg-emerald-500/10 text-emerald-700 border-emerald-200 dark:text-emerald-300 dark:border-emerald-700',
    manager_approval: 'bg-amber-500/10 text-amber-700 border-amber-200 dark:text-amber-300 dark:border-amber-700',
    manager_approved: 'bg-green-500/10 text-green-700 border-green-200 dark:text-green-300 dark:border-green-700',
    pending_conversion: 'bg-indigo-500/10 text-indigo-700 border-indigo-200 dark:text-indigo-300 dark:border-indigo-700',
    converted: 'bg-teal-500/10 text-teal-700 border-teal-200 dark:text-teal-300 dark:border-teal-700',
    deferred: 'bg-orange-500/10 text-orange-700 border-orange-200 dark:text-orange-300 dark:border-orange-700',
    rejected: 'bg-red-500/10 text-red-700 border-red-200 dark:text-red-300 dark:border-red-700',
    requires_more_info: 'bg-cyan-500/10 text-cyan-700 border-cyan-200 dark:text-cyan-300 dark:border-cyan-700'
  };
  return statusColors[status || 'generated'] ?? statusColors['generated'] ?? '';
}

export function getWorkflowStatusLabel(status: string): string {
  const labels: Record<string, string> = {
    generated: 'Generated',
    acknowledged: 'Acknowledged',
    under_review: 'Under Review',
    meeting_scheduled: 'Meeting Scheduled',
    initially_approved: 'Initially Approved',
    manager_approval: 'Pending Final Approval',
    manager_approved: 'Approved',
    pending_conversion: 'Pending Conversion',
    converted: 'Converted to Project',
    deferred: 'Deferred',
    rejected: 'Rejected',
    requires_more_info: 'More Info Required'
  };
  return labels[status] || status;
}
